# -*- coding: utf-8 -*-
"""CodeAlpha_Task2_Chatbot_For_FAQs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9k-9p21MX3upLdU1gl_44jsPWBJiUB2

# Collect_FAQs_Question&Answer
"""

faq = {
    "delivery": "Delivery 3-5 working days mein ho jati hai, aur 150 PKR delivery charges hain, 2000+ order free.",
    "cash_on_delivery": "Ji han, Cash on Delivery available hai",
    "return_policy": "7 din ke andar return/refund kar sakte hain",
    "size_exchange": "Ji, size exchange 3 din mein ho jaye ga",
    "payment_methods": "COD, JazzCash, Easypaisa, Bank Transfer",
    "track_order": "Order ID se humari website par track kar sakte hain",
    "product_authentic": "Ji, 100% original products with warranty",
    "discount": "Har month sale hoti hai, Instagram follow karen",
    "contact_number": "Customer care: 03xx-xxxxxxx, 9am-9pm"
}
categories = {
    "delivery": ["delivery", "kitne din", "kab", "shipping"],
    "cash_on_delivery": ["cash on delivery", "COD", "cash delivery"],
    "return_policy": ["return", "return policy", "kya hai", "kab tak"],
    "size_exchange": ["size exchange", "size change"],
    "payment_methods": ["payment methods", "kon se hain"],
    "track_order": ["track", "order kaise track karun"],
    "product_authentic": ["product original", "product asli", "product sahi hai"],
    "discount": ["discount", "discount kab lagta hai", "discount kitna"],
    "contact_number": ["contact number", "aap ka number", "customer care"]
}

"""#Install_scikit-learn-NLTK"""

!pip install scikit-learn nltk ipywidgets

"""#Preprocess_the_text"""

import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [lemmatizer .lemmatize(w) for w in tokens if w not in string.punctuation]
    stop_words = set(stopwords.words('english'))
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]
    return ' '.join(tokens)

"""#Check_Preprocess_Text"""

print(preprocess("Delivery kitne din me hoti hai???"))
print(preprocess("Return policy kya hai???"))

"""#Match_User_Question


"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def get_response(user_input):
    user_input_clean = preprocess(user_input)

    # Check categories
    for category, keywords in categories.items():
        if any(keyword in user_input_clean for keyword in keywords):
            return faq[category]

    # Existing greetings and goodbye
    greetings = ["hi", "hello", "hey", "assalam o alikum"]
    goodbye = ["bye", "okay", "allah hafiz"]

    questions = list(faq.keys())
    questions.append(user_input_clean)

    vectorizer = TfidfVectorizer().fit_transform(questions)
    vectors = vectorizer.toarray()

    similarity = cosine_similarity(vectors[-1].reshape(1, -1), vectors[:-1])
    max_idx = similarity.argmax()

    if similarity[0][max_idx] > 0.4:
        return faq[questions[max_idx]]
    elif user_input_clean in greetings:
        return "Assalam o alikum ji, main aap ki kya madad kar sakti hun?"
    elif user_input_clean in goodbye:
        return "Allah Hafiz"
    else:
        return "Sorry, mujhe samajh nahi aaya. Kya aap dobara pooch sakte hain?"

"""#Display_the_best_matching_answer"""

print(get_response("Delivery kitne din me hoti hai???"))
print(get_response("Return policy batao"))
print(get_response("Hello"))

"""#Create_a_simple_Chat_UI"""

import ipywidgets as widgets
from IPython.display import display
from ipywidgets import Output

text_box = widgets.Textarea(
    value='',
    placeholder='Ask your question here',
    description='Question:',
    layout=widgets.Layout(width='500px', height='80px')
)

btn = widgets.Button(
    description="Send",
    button_style='success'
)

output = Output()

def on_button_click(b):
    with output:
        user_q = text_box.value
        if user_q.strip():
            print("You:", user_q)
            print("Bot:", get_response(user_q))
            text_box.value = ''
        else:
            print("Please enter any question")

btn.on_click(on_button_click)
display(text_box, btn, output)